api_login_check:
  path: /api/login_check

admin_dashboard:
  path: /admin

admin_league:
  path: /admin/league
  controller: App\Controller\Admin\LeagueController::createLeague

register:
  path: /api/register
  controller: App\Controller\User\RegisterController::register
  methods: "POST"